USE BTS;


SELECT * FROM CUSTOMERS;
SELECT * FROM USERS;
SELECT * FROM ROLES;
SELECT * FROM TASK_DETAILS_UPDATE;
SELECT * FROM TASK_OWNERS;
SELECT * FROM REQUESTS;
SELECT * FROM TASKS;
SELECT * FROM CE_SKILLS;
SELECT * FROM QUEUES;
SELECT * FROM STATUS_TYPES;
SELECT * FROM TASK_TYPES;