USE BTS;

SELECT * FROM CUSTOMERS;
SELECT * FROM USERS;
SELECT * FROM ROLES;
SELECT * FROM REQUESTS;
SELECT * FROM TASKS;
SELECT * FROM QUEUES;
SELECT * FROM STATUS_TYPES;
SELECT * FROM TASK_TYPES;
SELECT * FROM SKILL_MAPPINGS;
SELECT 8 FROM KNOWLEDGE_MAPPINGS;

